### ISSUE TITLE
Bug for extract_tsr_patches.py

### ISSUE THREAD

**Issue by christianhi123** [zenseact/zod#24]
I am using the zod/cli/extract_tsr_patches.py script and I am running into the following error:

`TypeError: _process_frame() missing 1 required positional argument: 'train_ids'`

The output-folder and dataset-root flag have been defined to the correct location and I the ZodFrames class has been correctly instantiated. 

Adding the train_frame_ids before the call to `process_map` and giving the train_frame_ids as args only partially solves the error. Some patches are generated but the code fails at a certain point and the subsequent error is:

`TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'` from the process_map call.

**Comment by wljungbergh** [comment]
Thanks for raising this issue. 
- There was a bug in the argument passing as pointed out, which has now been fixed.
- There was a bug that arose due to the unclear traffic sign property. It has now been resolved by placing them in a "unclear" folder.

**Comment by christianhi123** [comment]
I think it is still not working if some annotations don't have traffic signs:

Error:

```
AssertionError: Project AnnotationProject.TRAFFIC_SIGNS not available.
```

What could fix this in the process_frame function:

```
try:
        traffic_signs: List[parser.TrafficSignAnnotation] = frame.get_annotation(
            constants.AnnotationProject.TRAFFIC_SIGNS
        )
except AssertionError:
        return []
```

**Comment by wljungbergh** [comment]
Sorry for the late reply, we have resolved it now (see #45)
